[package]
name = "day06"
version = "0.1.0"
authors = ["Marcel Mathé <m.mathe@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
regex = "1"

